FROM node:16-alpine

WORKDIR /app

COPY ./.sequelizerc .

COPY ./database ./database

COPY package*.json ./

RUN npm install sequelize-cli

RUN apk update && apk add bash

CMD ["sh", "/app/database/scripts/migrate.sh"]

