FROM node:16-alpine

WORKDIR /app

COPY ./.sequelizerc .

COPY ./database ./database

RUN npm init -y

RUN npm install sequelize pg pg-hstore sequelize-cli

RUN apk update && apk add bash

CMD ["sh", "/app/database/scripts/migrate.sh"]

