FROM node:16-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY  ./.production.env .

COPY ./.sequelizerc .

COPY ./database ./database

COPY ./scripts/ ./scripts/

COPY package*.json ./

RUN npm install sequelize-cli

RUN apk update && apk add bash

CMD ["sh", "/app/scripts/migrate.sh"]

